### ISSUE TITLE
difference between repo and demo?

### ISSUE THREAD

**Issue by ohNegative** [row1/brunch-materialistic-arrogantular#1]
In your demo located [here](http://row1.github.io/brunch-materialistic-arrogantular/#/)

the grid tiles are styled like this:

```
<md-grid-tile ng-repeat="gridTitle in homeCtrl.grid" md-rowspan="2" md-colspan="2" md-colspan-sm="1" ng-click="$state.go('posts.detail', { id: gridTitle.id })" class="ng-scope ng-isolate-scope" role="listitem" tabindex="0" style="left: calc(((25% - 6px) + 8px) * 0); width: calc(((25% - 6px) * 2) + 8px); padding-top: calc(((25% - 6px) * 2) + 8px); margin-top: calc(((25% - 6px) + 8px) * 0);"><figure ng-transclude="">
    <img ng-src="http://placehold.it/150/30ac17" class="ng-scope" src="http://placehold.it/150/30ac17">
    <md-grid-tile-footer class="ng-scope"><figcaption ng-transclude="">
      <h3 class="ng-binding ng-scope">accusamus beatae ad</h3>
    </figcaption></md-grid-tile-footer>
  </figure></md-grid-tile>
```
I'm looking specifically at this code:

`style="left: calc(((25% - 6px) + 8px) * 0); width: calc(((25% - 6px) * 2) + 8px); padding-top: calc(((25% - 6px) * 2) + 8px); margin-top: calc(((25% - 6px) + 8px) * 0);"`

But in the code that's in the repo, the grid is then styled like this:

```
<md-grid-tile ng-repeat="gridTitle in homeCtrl.grid" md-rowspan="2" md-colspan="2" md-colspan-sm="2" ng-click="$state.go('posts.detail', { id: gridTitle.id })" class="ng-scope ng-isolate-scope" role="listitem" tabindex="0" style="left: calc(((12.5% - 7px) + 8px) * 0); width: calc(((12.5% - 7px) * 2) + 8px); padding-top: calc(((12.5% - 7px) * 2) + 8px); margin-top: calc(((12.5% - 7px) + 8px) * 0);"><figure ng-transclude="">
    <img ng-src="http://placehold.it/150/30ac17" class="ng-scope" src="http://placehold.it/150/30ac17">
    <md-grid-tile-footer class="ng-scope"><figcaption ng-transclude="">
      <h3 class="ng-binding ng-scope">accusamus beatae ad</h3>
    </figcaption></md-grid-tile-footer>
  </figure></md-grid-tile>
```

And I'm looking specifically at this code:

`style="left: calc(((12.5% - 7px) + 8px) * 0); width: calc(((12.5% - 7px) * 2) + 8px); padding-top: calc(((12.5% - 7px) * 2) + 8px); margin-top: calc(((12.5% - 7px) + 8px) * 0);`

So in your demo, the styling uses 25% and the repo I'm coding with uses 12%. I know since these are inline they are being generated by JS - but for some reason, I can't for the life of me, find where these are being set.

If you can point me in the right direction, it would solve a lot of my styling issues in relation to the grid.

Thanks,

Pete

**Comment by row1** [comment]
The demo was written in an earlier version of Angular Material. The Angular Material upgrade was quite big and a lot changed. I couldn't get the grid tiles demo fully working quickly, so I published it thinking that updating the dependencies and some other layout issues was more important than fixing my specific grid tile issue.

**Comment by ohNegative** [comment]
Okay, thanks for the update, I appreciate it.

Pete
